import mongoose from 'mongoose'

const cancerReporteSchema = new mongoose.Schema({
  primerNombreUsuario: { type: String, required: true },
  segundoNombreUsuario: { type: String },
  primerApellidoUsuario: { type: String, required: true },
  segundoApellidoUsuario: { type: String },
  tipoIdentificacionUsuario: { type: String, required: true },
  numeroIdentificacionUsuario: { type: String, required: true },
  fechaNacimiento: { type: String, required: true },
  sexo: { type: String, enum: ['M','F'], required: true },
  ocupacion: { type: String },
  regimenAfiliacionSGSSS: { type: String, required: true },
  codigoEPS: { type: String, required: true },
  codigoPertenenciaEtnica: { type: String },
  grupoPoblacional: { type: String },
  municipioResidencia: { type: String },
  telefonoPaciente: { type: String },
  fechaAfiliacionEPS: { type: String },
  nombreNeoplasiaMaligna: { type: String, required: true },
  fechaDiagnosticoActual: { type: String, required: true },
  fechaNotaRemision: { type: String },
  fechaIngresoInstitucionDiagnostico: { type: String },
  tipoEstudioDiagnostico: { type: String },
  motivoSinHistopatologia: { type: String },
  fechaRecoleccionMuestra: { type: String },
  fechaInformeHistopatologico: { type: String },
  codigoIpsConfirmacionDiagnostico: { type: String },
  fechaPrimeraConsultaTratante: { type: String },
  histologiaTumor: { type: String },
  gradoDiferenciacion: { type: String },
  primeraEstadificacion: { type: String },
  fechaPrimeraEstadificacion: { type: String },
  her2RealizadoMama: { type: String },
  fechaPrimeraPruebaHer2: { type: String },
  resultadoUltimaPruebaHer2: { type: String },
  estadificacionDukesColorrectal: { type: String },
  fechaDukes: { type: String },
  estadificacionClinicaHematologica: { type: String },
  escalaGleasonProstata: { type: String },
  clasificacionRiesgo: { type: String },
  fechaClasificacionRiesgo: { type: String },
  objetivoTratamientoInicial: { type: String },
  objetivoIntervencionPeriodo: { type: String },
  antecedenteOtroCancer: { type: String },
  fechaDiagnosticoOtroCancer: { type: String },
  tipoOtroCancerCIE10: { type: String },

  // Tratamientos sistémicos
  recibioQuimioterapiaSistemaPeriodo: { type: String },
  fasesQuimioterapiaHematolinfaticas: { type: Number },
  fasePrefase: { type: String },
  faseInduccion: { type: String },
  faseIntensificacion: { type: String },
  faseConsolidacion: { type: String },
  faseReinduccion: { type: String },
  faseMantenimiento: { type: String },
  faseMantenimientoLargo: { type: String },
  faseOtra: { type: String },
  numeroCiclosRecibidos: { type: Number },
  ubicacionTemporalPrimerEsquema: { type: String },
  fechaInicioPrimerEsquema: { type: String },
  numeroIpsPrimerEsquema: { type: Number },
  codigoIps1PrimerEsquema: { type: String },
  codigoIps2PrimerEsquema: { type: String },
  numeroMedicamentosPropuestosPrimerEsquema: { type: Number },
  medicamento1PrimerEsquema: { type: String },
  medicamento2PrimerEsquema: { type: String },
  medicamento3PrimerEsquema: { type: String },
  medicamento4PrimerEsquema: { type: String },
  medicamento5PrimerEsquema: { type: String },
  medicamento6PrimerEsquema: { type: String },
  medicamento7PrimerEsquema: { type: String },
  medicamento8PrimerEsquema: { type: String },
  medicamento9PrimerEsquema: { type: String },
  medicamento10PrimerEsquema: { type: String },
  medicamento11PrimerEsquema: { type: String },
  medicamento12PrimerEsquema: { type: String },
  recibioIntratecalPrimerCiclo: { type: String },
  fechaFinPrimerCiclo: { type: String },
  caracteristicasPrimerCiclo: { type: String },
  motivoTerminacionPrematuraPrimerCiclo: { type: String },
  ubicacionTemporalUltimoCiclo: { type: String },
  fechaInicioUltimoCiclo: { type: String },
  numeroIpsUltimoCiclo: { type: Number },
  codigoIps1UltimoCiclo: { type: String },
  codigoIps2UltimoCiclo: { type: String },
  numeroMedicamentosPropuestosUltimoCiclo: { type: Number },
  medicamento1UltimoCiclo: { type: String },
  medicamento2UltimoCiclo: { type: String },
  medicamento3UltimoCiclo: { type: String },
  medicamento4UltimoCiclo: { type: String },
  medicamento5UltimoCiclo: { type: String },
  medicamento6UltimoCiclo: { type: String },
  medicamento7UltimoCiclo: { type: String },
  medicamento8UltimoCiclo: { type: String },
  medicamento9UltimoCiclo: { type: String },
  medicamento10UltimoCiclo: { type: String },
  medicamento11UltimoCiclo: { type: String },
  medicamento12UltimoCiclo: { type: String },
  recibioIntratecalUltimoCiclo: { type: String },
  fechaFinUltimoCiclo: { type: String },
  caracteristicasUltimoCiclo: { type: String },
  motivoTerminacionPrematuraUltimoCiclo: { type: String },

  // Cirugías
  recibioCirugiaCurativaPaliativa: { type: String },
  numeroCirugiasPeriodo: { type: Number },
  fechaPrimeraCirugia: { type: String },
  codigoIpsPrimeraCirugia: { type: String },
  codigoPrimeraCirugia: { type: String },
  ubicacionTemporalPrimeraCirugia: { type: String },
  fechaUltimaCirugia: { type: String },
  motivoUltimaCirugia: { type: String },
  codigoIpsUltimaCirugia: { type: String },
  codigoUltimaCirugia: { type: String },
  ubicacionTemporalUltimaCirugia: { type: String },
  estadoVitalPostCirugia: { type: String },

  // Radioterapia
  recibioRadioterapia: { type: String },
  numeroSesionesRadioterapia: { type: Number },
  fechaInicioRadioterapia: { type: String },
  ubicacionTemporalPrimerEsquemaRadioterapia: { type: String },
  tipoRadioterapiaPrimer: { type: String },
  numeroIpsPrimerRadioterapia: { type: Number },
  codigoIps1PrimerRadioterapia: { type: String },
  codigoIps2PrimerRadioterapia: { type: String },
  fechaFinPrimerRadioterapia: { type: String },
  caracteristicasPrimerRadioterapia: { type: String },
  motivoFinPrimerRadioterapia: { type: String },
  fechaInicioUltimoRadioterapia: { type: String },
  ubicacionTemporalUltimoEsquemaRadioterapia: { type: String },
  tipoRadioterapiaUltimo: { type: String },
  numeroIpsUltimoRadioterapia: { type: Number },
  codigoIps1UltimoRadioterapia: { type: String },
  codigoIps2UltimoRadioterapia: { type: String },
  fechaFinUltimoRadioterapia: { type: String },
  caracteristicasUltimoRadioterapia: { type: String },
  motivoFinUltimoRadioterapia: { type: String },

  // Trasplante
  recibioTrasplanteProgenitoras: { type: String },
  tipoTrasplante: { type: String },
  ubicacionTemporalTrasplante: { type: String },
  fechaTrasplante: { type: String },
  codigoIpsTrasplante: { type: String },
  cirugiaReconstructiva: { type: String },
  fechaCirugiaReconstructiva: { type: String },
  codigoIpsCirugiaReconstructiva: { type: String },

  // Cuidados paliativos y otras consultas
  valoradoPaliativo: { type: String },
  paliativoEspecialista: { type: String },
  paliativoProfesionalNoMedico: { type: String },
  paliativoOtraEspecialidad: { type: String },
  paliativoMedicoGeneral: { type: String },
  paliativoTrabajoSocial: { type: String },
  paliativoOtroProfesional: { type: String },
  fechaPrimeraValoracionPaliativo: { type: String },
  codigoIpsPaliativo: { type: String },

  valoradoPsiquiatria: { type: String },
  fechaPrimeraConsultaPsiquiatria: { type: String },
  codigoIpsPsiquiatria: { type: String },

  valoradoNutricion: { type: String },
  fechaConsultaNutricion: { type: String },
  codigoIpsNutricion: { type: String },

  recibioSoporteNutricional: { type: String },
  recibioTerapiasComplementarias: { type: String },
  tipoTratamientoFechaCorte: { type: String },
  resultadoFinalManejoOncologico: { type: String },
  estadoVitalFinalCorte: { type: String },
  novedadAdministrativa: { type: String },
  novedadClinica: { type: String },
  fechaDesafiliacionEPS: { type: String },
  fechaMuerte: { type: String },
  causaMuerte: { type: String },
  codigoUnicoIdentificacion: { type: String }
});

export default mongoose.model('CancerReporte', cancerReporteSchema);
